    version: '2'
    services:
      web:
        build: .
        ports:
         - "9999:9999"
        volumes:
         - .:/code
        links:
         - redis
        depends_on:
         - redis
      redis:
        image: redis
        ports:
         - "6379:6379"
