    version: '2'
    services:
      web:
        build: .
        ports:
         - "9999:9999"
        volumes:
         - .:/code
        depends_on:
         - db
      db:
       image: mysql
       ports:
         - "3306:3306"
       environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_USER: root
         MYSQL_PASSWORD:
         MYSQL_DATABASE: open-versus
