    version: '2'
    services:
      web:
        build: .
        ports:
         - "9999:9999"
        volumes:
         - .:/code
        depends_on:
         - redis
      redis:
        image: redis
