    version: '2'
    services:
      web:
        build: .
        ports:
         - "9999:9999"
        volumes:
         - .:/code
        links:
         - db
         - redis
         depends_on:
         -  db
         -  redis
      db:
       image: mysql
       ports:
         - "3306"
       environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_USER: root
         MYSQL_PASSWORD:
         MYSQL_DATABASE: open-versus
      redis:
        image: redis
        ports:
          - "6379"